artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Nexaaman/Datasets/raw/main/CogniText.zip
  data_path: artifacts/data_ingestion/Data.zip
  save_dir: artifacts/data_ingestion